### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stelfrich** [petebankhead/imagej-intro#1]
Hi @petebankhead.

First of all: thank you for your amazing work on this intro!

I was wondering about the license of the book and its contents. The only thing I could find w.r.t. licensing is the https://github.com/petebankhead/imagej-intro/blob/master/disclaimer.adoc which seems rather unspecific. Have you thought about licensing the book under, for example, a Creative Commons license (maybe [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)) so that people can re-use contents of the book?

Best,
Stefan

**Comment by petebankhead** [comment]
I realise this reply is more than 5 years late, but the updated (now CC-BY) version is at https://bioimagebook.github.io/ :)

**Comment by petebankhead** [comment]
I'll close this, since I can't update it anyway on GitBook. https://github.com/bioimagebook is where the new stuff will be...
